# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # 2) 构建项目
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 1 安装 node 环境
      - name: Setup Node.js (设置 node 版本)
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm (安装 pnpm)
        uses: pnpm/action-setup@v2
        with:
          version: 8
      # 2 安装检索依赖
      - name: Install Dependencies(安装依赖)
        run: pnpm i
      # 3 构建项目
      - name: Build(构建项目)
        run: pnpm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
